models/User.php
<?php

namespace app\models;

use Yii;
use app\models\Log;
use yii\db\Exception;
use yii\helpers\Json;
use app\models\Jabatan;
use app\models\AuthItem;
use app\models\Struktur;
use app\models\UserMeta;
use yii\db\ActiveRecord;
use app\models\Perusahaan;
use yii\helpers\ArrayHelper;
use app\models\AuthAssignment;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string|null $nama
 * @property string|null $email
 * @property string|null $username
 * @property string|null $password_hash
 * @property string|null $auth_key
 * @property string|null $password_reset_token
 * @property string|null $verification_token
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property string|null $deleted_at
 *
 * @property Transaksi[] $transaksis
 * @property UserMeta[] $userMetas
 */

class User extends ActiveRecord implements IdentityInterface
{
    public $nama_perusahaan;
    public $telpn_perusahaan;
    public $alamat_perusahaan;
    public $email_perusahaan;
    public $new_password;
    public $jabatan_id;

    const scenario_create = 'create';
    const scenario_update = 'update';
    const scenario_register = 'register';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    public function requiredMessage()
    {
        return '{attribute} '.Yii::t('app', 'Wajib Diisi');
    }

    public function uniqueMessage()
    {
        return '{attribute} '.Yii::t('app', 'Sudah terdaftar');
    }

    public function rulesRegisterRequired()
    {
        return [
            [
                'nama', 
                'email', 
                'username', 
                'password_hash', 
                'nama_perusahaan', 
                'telpn_perusahaan', 
                'alamat_perusahaan',
                'email_perusahaan'
            ],
            'required', 
            'message' => self::requiredMessage(),
            'on' => 'register', 
        ];
    }

    public function rulesCreateRequired()
    {
        return [
            [
                'nama', 
                'email', 
                'username', 
                'password_hash', 
                'jabatan_id',
            ],
            'required', 
            'message' => self::requiredMessage(),
            'on' => 'create', 
        ];
    }

    public function rulesUpdateRequired()
    {
        return [
            [
                'nama', 
                'email', 
                'username',
                'jabatan_id'
            ],
            'required', 
            'message' => self::requiredMessage(),
            'on' => 'update', 
        ];
    }

    public function rulesRegisterUnique()
    {
        return [
            [
                'email', 
                'username',
            ],
            'unique',
            'message' => self::uniqueMessage(),
            'on' => 'register', 
        ];
    }

    public function rulesCreateUnique()
    {
        return [
            [
                'email', 
                'username',
            ],
            'unique',
            'message' => self::uniqueMessage(),
            'on' => 'create', 
        ];
    }

    public function rulesUpdateUnique()
    {
        return [
            [
                'email', 
                'username',
            ],
            'unique',
            'message' => self::uniqueMessage(),
            'on' => 'create', 
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['deleted_at'], 'safe'],
            [['nama'], 'string', 'max' => 150],
            [['email', 'username'], 'string', 'max' => 50],
            [['password_hash', 'new_password'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 191],
            [['password_reset_token', 'verification_token'], 'string', 'max' => 200],
            self::rulesRegisterRequired(),
            self::rulesRegisterUnique(),

            self::rulesCreateRequired(),
            self::rulesCreateUnique(),

            self::rulesUpdateRequired(),
            self::rulesUpdateUnique(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nama' => Yii::t('app', 'Nama'),
            'email' => Yii::t('app', 'Email'),
            'username' => Yii::t('app', 'Username'),
            'password_hash' => Yii::t('app', 'Password'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'jabatan_id' =>  Yii::t('app', 'Jabatan'),
            'nama_perusahaan' => Yii::t('app', 'Nama Perusahaan'),
            'telpn_perusahaan' => Yii::t('app', 'No Telepon Perusahaan'),
            'alamat_perusahaan' => Yii::t('app', 'Alamat Perusahaan'),
            'email_perusahaan' => Yii::t('app', 'Email Perusahaan'),
            'new_password' => Yii::t('app', 'Password'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'verification_token' => Yii::t('app', 'Verification Token'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'deleted_at' => Yii::t('app', 'Deleted At'),
        ];
    }
    
    public function scenarios() {
        $scenarios = parent::scenarios();
        $scenarios['update'] = ['nama', 'email', 'username', 'new_password', 'jabatan_id'];
        $scenarios['create'] = ['password_hash', 'nama', 'email', 'username', 'jabatan_id'];
        $scenarios['register'] = [
            'nama', 
            'email',
            'username',
            'password_hash',
            'email_perusahaan',
            'nama_perusahaan',
            'telpn_perusahaan',
            'alamat_perusahaan'
        ];
        
        return $scenarios;
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                 'class' => 'yii\behaviors\TimestampBehavior',
                 'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                 ],
             ],
        ];
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeuangans()
    {
        return $this->hasMany(Keuangan::className(), ['user_id' => 'id']);
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserMetas()
    {
        return $this->hasMany(UserMeta::className(), ['user_id' => 'id']);
    }

    public function getStruktur()
    {
        return $this->hasOne(Struktur::className(), ['user_id' => 'id'])->where(['perusahaan_id' => Perusahaan::findDataPerusahaan()->id]);
    }

    public function getRole()
    {
        return array_keys(Yii::$app->authManager->getAssignments(Yii::$app->user->identity->id))[0];
    }

    public static function findUser()
    {
        return Yii::$app->user->identity;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'deleted_at' => null]);
    }

    public static function listUser()
    {
        $user = static::find()
        ->where(['deleted_at' => null])
        ->all();

        return ArrayHelper::map($user, 'id','nama');
    }
    

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token, 'deleted_at' => null]);
        // throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'deleted_at' => null]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'deleted_at' => null,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'deleted_at' => null
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Jabatan;
use yii\web\Controller;
use app\models\Struktur;
use app\models\UserMeta;
use yii\filters\VerbFilter;
use app\models\search\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for Users model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted_at' => null]);
        $dataProvider->query->andWhere(['IN', 'id', Struktur::findKaryawanId()]);
        // debug(Struktur::findKaryawanId());

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel(decrypt($id));
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));
        $model->scenario = 'update';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->updateUser(decrypt($id))) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['view', 'id' => encrypt($model->id)]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        User::softDelete(decrypt($id));
        
        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'jabatan_id')->dropDownList($jabatan, ['prompt' => 'Pilih', 'value' => ($model->isNewRecord) ? '' : $model->struktur->jabatan_id])?>

        <?php if ($model->isNewRecord) {?>
            <?= $form->field($model, 'password_hash')->passwordInput(['maxlength' => true]) ?>
        <?php }else{?>
            <?= $form->field($model, 'new_password')->passwordInput(['maxlength' => true]) ?>
        <?php } ?>
        

    </div>
    <div class="box-footer">
        <?= Html::submitButton('<i class="fa fa-floppy-o" aria-hidden="true"></i> '.Yii::t('app', 'Simpan'), ['class' => 'btn btn-success btn-flat']) ?>
        <?= Html::a('<i class="fa fa-ban" aria-hidden="true"></i> '.Yii::t('app', 'Batal'),['user/index'], ['class' => 'btn btn-danger btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'verification_token') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'deleted_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = Yii::t('app', 'Tambah Pengguna');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengguna'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <?= $this->render('_form', [
        'model' => $model,
        'jabatan' => $jabatan,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\grid\GridView;
use mdm\admin\components\Helper;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'List Pengguna');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index box box-primary">
    <?php Pjax::begin(['enablePushState' => false]); ?>
    <div class="box-header with-border">
        <?php //Html::a(Yii::t('app', 'T Users'), ['create'], ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                // 'id',
                'nama',
                'email:email',
                'username',
                // 'password_hash',
                // 'auth_key',
                // 'password_reset_token',
                // 'verification_token',
                // 'created_at',
                // 'updated_at',
                // 'deleted_at',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => Helper::filterActionColumn('{view} {update} {delete}'),
                    'buttons' => [
                        'view' => function($url, $model, $key){
                            return Html::a('<i class="fa fa-eye" aria-hidden="true"></i>', ['view', 'id' => encrypt($model->id)], ['class' => 'btn btn-info btn-flat']);
                        },
                        'update' => function($url, $model, $key){
                            return Html::a('<i class="fa fa-pencil-square-o" aria-hidden="true"></i> ', ['update', 'id' => encrypt($model->id)], ['class' => 'btn btn-warning flat']);
                        },
                        'delete' => function($url, $model, $key){
                            return Html::a('<i class="fa fa-trash" aria-hidden="true"></i>', ['delete', 'id' => encrypt($model->id)],[
                                'class' => 'btn btn-danger btn-flat',
                                'data' => [
                                    'confirm' => Yii::t('app', 'Anda yakin ingin menghapus data ini?'),
                                    'method' => 'post',
                                ]
                            ]);
                        }
                    ],
                ],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = Yii::t('app', 'Memperbarui {modelClass}: ', [
    'modelClass' => Yii::t('app', 'Pengguna'),
]) . $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengguna'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => encrypt($model->id)]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Memperbarui');
?>

<div class="users-update">
    <?= $this->render('_form', [
        'model' => $model,
        'jabatan' => $jabatan,
    ]) ?>
</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use mdm\admin\components\Helper;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengguna'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view box box-primary">
    <div class="box-header">
        <?php 
            if (Helper::checkRoute('update')) {
                echo Html::a('<i class="fa fa-pencil-square-o" aria-hidden="true"></i> '.Yii::t('app', 'Edit'), ['update', 'id' => encrypt($model->id)], ['class' => 'btn btn-primary btn-flat']);
            }
        ?>
        <?php
            if (Helper::checkRoute('delete')) {
                echo Html::a('<i class="fa fa-trash" aria-hidden="true"></i> '.Yii::t('app', 'Hapus'), ['delete', 'id' => encrypt($model->id)], [
                    'class' => 'btn btn-danger btn-flat',
                    'data' => [
                        'confirm' => Yii::t('app', 'Anda yakin ingin menghapus data ini?'),
                        'method' => 'post',
                    ],
                ]);
            }
        ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                // 'id',
                'nama',
                'email:email',
                'username',
                // 'password_hash',
                // 'auth_key',
                // 'password_reset_token',
                // 'verification_token',
                // 'created_at:datetime',
                // 'updated_at:datetime',
                // 'deleted_at',
            ],
        ]) ?>
    </div>
</div>