controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\helpers\Url;
use yii\web\Response;
use yii\web\Controller;
use app\models\Keuangan;
use app\models\Struktur;
use app\models\LoginForm;
use app\models\Perusahaan;
use app\models\ContactForm;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $sumKeuangan = Keuangan::sumKeuangan();
        $totalKaryawan = Struktur::totalKaryawan();
        $findPerusahaan = Perusahaan::findDataPerusahaan(User::findUser()->id);
        $sumAsset = Keuangan::sumAsset();

        // debug(Keuangan::sumAsset());
        
        return $this->render('index', [
            'sumKeuangan' => $sumKeuangan,
            'totalKaryawan' => $totalKaryawan,
            'findPerusahaan' => $findPerusahaan,
            'sumAsset' => $sumAsset
        ]);
    }
    

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister()
    {
        $user = new User();
        $user->scenario = 'register';

        

        if ($user->load(Yii::$app->request->post()) && $user->register()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil Mendaftar, silahkan login'));
            return $this->redirect(['login']);
        }

        return $this->render('register', [
            'user' => $user
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/template/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/template/site/login.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = Yii::t('app', 'Masuk');

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Management Officer</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg"><?= Yii::t('app', 'Masuk untuk memulai sesi Anda')?></p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel(Yii::t('app','username'))]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel(Yii::t('app','password'))]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox()->label(Yii::t('app', 'Ingat saya')) ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton(Yii::t('app', 'Masuk'), ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>

        <!-- <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div> -->
        <!-- /.social-auth-links -->

        <!-- <a href="#">I forgot my password</a><br> -->
        <a href="<?= Url::to(['site/register'])?>" class="text-center"><?= Yii::t('app', 'Daftarkan keanggotaan baru')?></a>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

views/template/site/register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Daftar';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Management Officer</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg"><?= Yii::t('app', 'Silakan isi kolom-kolom berikut untuk mendaftar: ')?></p>

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($user, 'username')->textInput(['autofocus' => true]) ?>
        <?= $form->field($user, 'email')->textInput(['autofocus' => true]) ?>
        <?= $form->field($user, 'nama')->textInput(['autofocus' => true]) ?>

        <?= $form->field($user, 'nama_perusahaan')->textInput(['autofocus' => true]) ?>
        <?= $form->field($user, 'telpn_perusahaan')->textInput(['autofocus' => true]) ?>
        <?= $form->field($user, 'alamat_perusahaan')->textInput(['autofocus' => true]) ?>
        <?= $form->field($user, 'email_perusahaan')->textInput(['autofocus' => true]) ?>

        <?= $form->field($user, 'password_hash')->passwordInput() ?>

        
        <!-- <div class="col-xs-4"> -->
            <?= Html::submitButton(Yii::t('app', 'Daftar'), ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
        <!-- </div> -->


        <?php ActiveForm::end(); ?>
        <br>
        <!-- <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div> -->
        <!-- /.social-auth-links -->

        <!-- <a href="#">I forgot my password</a><br> -->
        <a href="<?= Url::to(['site/login'])?>" class="text-center btn btn-info btn-block"><?= Yii::t('app', 'Masuk')?></a>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->