controllers/JabatanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Log;
use app\models\User;
use yii\db\Exception;
use app\models\Jabatan;
use yii\web\Controller;
use app\models\AuthItem;
use app\models\Struktur;
use app\models\Perusahaan;
use yii\filters\VerbFilter;
use app\models\AuthItemChild;
use yii\web\NotFoundHttpException;
use app\models\search\JabatanSearch;

/**
 * JabatanController implements the CRUD actions for Jabatan model.
 */
class JabatanController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Jabatan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JabatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['perusahaan_id' => Struktur::findPerusahaan()->perusahaan_id]);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Jabatan model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $listPermission = AuthItem::listPermission();
        $model = $this->findModel(decrypt($id));
        $findRole = AuthItemChild::find()
        ->where(['parent' => $model->role_perusahaan])
        ->all();
        // debug($findRole);


        if (Yii::$app->request->post()) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $permission = Yii::$app->request->post('hak_akses');
                foreach ($permission as $key => $value) {
                    $data[] = [
                        'parent' => $model->role_perusahaan,
                        'child' => $value
                    ];
                }
                AuthItemChild::deleteAll(['parent' => $model->role_perusahaan]);

                Yii::$app->db
                ->createCommand()
                ->batchInsert('auth_item_child', ['parent','child'],$data)
                ->execute();

                $transaction->commit();
                Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
                return $this->redirect(Yii::$app->request->referrer);
            } catch (Exception $th) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', Yii::t('app', 'Terjadi Kesalahan, silahkan coba lagi'));
                return $this->redirect(Yii::$app->request->referrer);
            }
        }
        
        return $this->render('view', [
            'model' => $model,
            'listPermission' => $listPermission,
            'findRole' => $findRole
        ]);
    }

    /**
     * Creates a new Jabatan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Jabatan();

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->perusahaan_id = Struktur::findPerusahaan()->perusahaan_id;
                $model->role_perusahaan = $_POST['Jabatan']['singkatan'].'_'.Perusahaan::findDataPerusahaan()->id;
                $model->save();

                $autItem = new AuthItem();
                $autItem->name = $model->singkatan.'_'.Perusahaan::findDataPerusahaan()->id;
                $autItem->type = 1;
                $autItem->description = $model->deskripsi;
                $autItem->save(false);

                $log = new Log();
                $log->user_id = User::findUser()->id;
                $log->perusahaan_id = Struktur::findPerusahaan()->perusahaan_id;
                $log->module = 'Jabatan';
                $log->fungsi = 'Create';
                $log->keterangan = User::findUser()->nama. ', membuat jabatan '.$model->nama;
                $log->tanggal = date('Y-m-d');
                $log->save(false);

                $transaction->commit();

                Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
                return $this->redirect(['view', 'id' => encrypt($model->id)]);
                
            } catch (Exception $th) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', Yii::t('app', 'Terjadi Kesalahan, silahkan coba lagi'));
                return $this->redirect(Yii::$app->request->referrer);
            }
            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Jabatan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->perusahaan_id = Struktur::findPerusahaan()->perusahaan_id;
                $model->role_perusahaan = $_POST['Jabatan']['singkatan'].'_'.Perusahaan::findDataPerusahaan()->id;
                $model->save();

                $autItem = AuthItem::findOne(['name' => $model->singkatan]);
                $autItem->name = $model->singkatan;
                $autItem->description = $model->deskripsi;
                $autItem->save(false);

                $log = new Log();
                $log->user_id = User::findUser()->id;
                $log->perusahaan_id = Struktur::findPerusahaan()->perusahaan_id;
                $log->module = 'Jabatan';
                $log->fungsi = 'Update';
                $log->keterangan = User::findUser()->nama. ', memperbarui jabatan '.$model->nama;
                $log->tanggal = date('Y-m-d');
                $log->save(false);

                $transaction->commit();

                Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
                return $this->redirect(['view', 'id' => decrypt($model->id)]);
            } catch (Exception $th) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', Yii::t('app', 'Terjadi Kesalahan, silahkan coba lagi'));
                return $this->redirect(Yii::$app->request->referrer);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Jabatan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        Jabatan::softDelete(decrypt($id));
        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Jabatan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Jabatan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Jabatan::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

controllers/KodeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Log;
use app\models\Kode;
use app\models\User;
use yii\web\Controller;
use app\models\UserMeta;
use app\models\Perusahaan;
use yii\filters\VerbFilter;
use app\models\search\KodeSearch;
use yii\web\NotFoundHttpException;

/**
 * KodeController implements the CRUD actions for Kode model.
 */
class KodeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kode models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KodeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted_at' => null]);
        $dataProvider->query->andWhere(['perusahaan_id' => Perusahaan::findDataPerusahaan()->id]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Kode model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel(decrypt($id)),
        ]);
    }

    /**
     * Creates a new Kode model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Kode();
        $perusahaan = Perusahaan::findDataPerusahaan();

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            
            $log = new Log();
            $log->user_id = User::findUser()->id;
            $log->perusahaan_id = Perusahaan::findDataPerusahaan()->id;
            $log->module = 'Kode';
            $log->fungsi = 'Create';
            $log->keterangan = User::findUser()->nama. ', menambah kode transaksi '.$model->kode.' '.$model->nama;
            $log->tanggal = date('Y-m-d');
            $log->save(false);

            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['view', 'id' => encrypt($model->id)]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'perusahaan' => $perusahaan
            ]);
        }
    }

    /**
     * Updates an existing Kode model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));
        $perusahaan = Perusahaan::findDataPerusahaan();

        if ($model->load(Yii::$app->request->post())) {

            $log = new Log();
            $log->user_id = User::findUser()->id;
            $log->perusahaan_id = Perusahaan::findDataPerusahaan()->id;
            $log->module = 'Kode';
            $log->fungsi = 'Update';
            $log->keterangan = User::findUser()->nama. ', memperbarui kode transaksi '.$model->kode.' '.$model->nama;
            $log->tanggal = date('Y-m-d');
            $log->save(false);

            $model->save();
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['view', 'id' => encrypt($model->id)]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'perusahaan' => $perusahaan
            ]);
        }
    }

    /**
     * Deletes an existing Kode model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        Kode::softDelete(decrypt($id));

        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Kode model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kode::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Jabatan;
use yii\web\Controller;
use app\models\Struktur;
use app\models\UserMeta;
use yii\filters\VerbFilter;
use app\models\search\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for Users model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted_at' => null]);
        $dataProvider->query->andWhere(['IN', 'id', Struktur::findKaryawanId()]);
        // debug(Struktur::findKaryawanId());

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel(decrypt($id));
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));
        $model->scenario = 'update';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->updateUser(decrypt($id))) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['view', 'id' => encrypt($model->id)]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        User::softDelete(decrypt($id));
        
        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

views/template/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2019 - <?= date('Y')?> <a href="#">DigigiD</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/template/layouts/left.php
<?php

use app\models\User;
use dmstr\widgets\Menu;
use mdm\admin\components\Helper;

?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= User::findUser()->nama?></p>

                <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
            </div>
        </div>

        <!-- search form -->
        <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form> -->
        <!-- /.search form -->
        <?php
            $menuItems = [
                ['label' => Yii::t('app', 'Menu Navigation'), 'options' => ['class' => 'header']],
                ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii']],

                [
                    'label' => Yii::t('app', 'Beranda'),
                    'icon' => 'fas fa-home',
                    'url' => ['/site/index'],
                ],
                [
                    'label' => Yii::t('app', 'Jabatan'),
                    'icon' => 'fas fa-sitemap',
                    'url' => '#',
                    'items' => [
                        [
                            'label' => Yii::t('app', 'List'),
                            'icon' => 'fas fa-list',
                            'url' => ['/jabatan/index'],
                        ],
                        [
                            'label' => Yii::t('app', 'Tambah'),
                            'icon' => 'fas fa-plus',
                            'url' => ['/jabatan/create'],
                        ],
                    ],
                ],
                [
                    'label' => Yii::t('app', 'Pengguna'),
                    'icon' => 'fas fa-user',
                    'url' => '#',
                    'items' => [
                        [
                            'label' => Yii::t('app', 'List Pengguna'),
                            'icon' => 'fas fa-list',
                            'url' => ['/user/index'],
                        ],
                        [
                            'label' => Yii::t('app', 'Tambah Pengguna'),
                            'icon' => 'fas fa-user-plus',
                            'url' => ['/user/create'],
                        ],
                    ],
                ],
                [
                    'label' => Yii::t('app', 'Hak Akses'), 
                    'icon' => 'fas fa-user-secret', 
                    'url' => '#',
                    'items' => [
                        [
                            'label' => Yii::t('app', 'Route'),
                            'icon' => 'fas fa-circle-o',
                            'url' => ['/admin/route'],
                        ],
                        [
                            'label' => Yii::t('app', 'Permission'),
                            'icon' => 'fas fa-circle-o',
                            'url' => ['/admin/permission'],
                        ],
                        [
                            'label' => Yii::t('app', 'Role'),
                            'icon' => 'fas fa-circle-o',
                            'url' => ['/admin/role'],
                        ],
                        [
                            'label' => Yii::t('app', 'Assignment'),
                            'icon' => 'fas fa-circle-o',
                            'url' => ['/admin/assignment'],
                        ]
                    ],
                ],

                [
                    'label' => Yii::t('app', 'Kode Transaksi'),
                    'icon' => 'fas fa-book',
                    'url' => '#',
                    'items' => [
                        [
                            'label' => Yii::t('app', 'List Kode Keuangan'),
                            'icon' => 'fas fa-list',
                            'url' => ['/kode/index'],
                        ],
                        [
                            'label' => Yii::t('app', 'Tambah Kode'),
                            'icon' => 'fas fa-plus',
                            'url' => ['/kode/create'],
                        ],
                    ],
                ],

                [
                    'label' => Yii::t('app', 'Keuangan'),
                    'icon' => 'fas fa-money',
                    'url' => '#',
                    'items' => [
                        [
                            'label' => Yii::t('app', 'List'),
                            'icon' => 'fas fa-list',
                            'url' => ['/keuangan/index'],
                        ],
                        [
                            'label' => Yii::t('app', 'Tambah'),
                            'icon' => 'fas fa-plus',
                            'url' => ['/keuangan/create'],
                        ],
                    ],
                ],
                
            ];
        ?>
        
        <?php $menuItems = Helper::filter($menuItems); ?>
        <?= Menu::widget([
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => $menuItems
            ]) ?>

    </section>

</aside>

views/template/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>