controllers/KeuanganController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kode;
use app\models\User;
use yii\web\Controller;
use app\models\Keuangan;
use app\models\UserMeta;
use app\models\Perusahaan;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use app\models\search\KeuanganSearch;

/**
 * KeuanganController implements the CRUD actions for Keuangan model.
 */
class KeuanganController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Keuangan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $perusahaan = Perusahaan::findDataPerusahaan();
        $searchModel = new KeuanganSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['perusahaan_id' => $perusahaan->id]);
        $listKode = Kode::listKode();

        if (Yii::$app->request->get('filter_tanggal')) {
            $tanggal = Yii::$app->request->get('filter_tanggal');
            $explode = explode(" - ", $tanggal);
            $startDate = $explode[0];
            $endDate = $explode[1];
            
            $keuangan = Keuangan::find()
            ->where(['between', 'tanggal', $startDate, $endDate])
            ->andWhere(['perusahaan_id' => $perusahaan->id])
            ->all();

            // debug($keuangan);

            $pemasukkan = Keuangan::sumPemasukkan($startDate, $endDate);
            $pengeluaran = Keuangan::sumPengeluaran($startDate, $endDate);
            $selisih = $pemasukkan - $pengeluaran;
            
            ob_get_clean();
            $filename = 'Laporan Keuangan '.$perusahaan->nama_perusahaan.' '.indonesian_date($startDate, 'j F Y').' - '.indonesian_date($endDate, 'j F Y').'.xls';
            header("Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            header("Content-Disposition: attachment;Filename=".$filename);

            if (!empty($keuangan)) {
                return $this->renderPartial('laporan', [
                    'query' => $keuangan,
                    'startDate' => $startDate,
                    'endDate' => $endDate,
                    'perusahaan' => $perusahaan,
                    'pemasukkan' => $pemasukkan,
                    'pengeluaran' => $pengeluaran,
                    'selisih' => $selisih
                ]);
            }else{
                Yii::$app->session->setFlash('error', Yii::t('app', 'Laporan keuangan tidak ditemukan'));
                return $this->redirect(['index']);
            }
            
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'listKode' => $listKode
        ]);
    }

    // public function laporan($tanggal)
    // {
    //     $explode = explode(" - ", $tanggal);
    //     $startDate = $explode[0];
    //     $endDate = $explode[1];
        
    //     $keuangan = Keuangan::find()
    //     ->where(['between', 'tanggal', $startDate, $endDate])
    //     ->andWhere(['perusahaan_id' => UserMeta::findOwner(User::findUser()->id)->id])
    //     ->all();

    //     $perusahaan = UserMeta::findDataPerusahaan(User::findUser()->id);

    //     $pemasukkan = Keuangan::sumPemasukkan($startDate, $endDate);
    //     $pengeluaran = Keuangan::sumPengeluaran($startDate, $endDate);
    //     $selisih = $pemasukkan - $pengeluaran;
    //     // debug($pengeluaran);
    //     // ob_start();
    //     ob_get_clean();
    //     $filename = 'Laporan Keuangan '.$perusahaan->nama_perusahaan.' '.indonesian_date($startDate, 'j F Y').' - '.indonesian_date($endDate, 'j F Y').'.xls';
    //     header("Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    //     header("Content-Disposition: attachment;Filename=".$filename);
    //     // ob_end_flush();

    //     return $this->renderPartial('laporan', [
    //         'query' => $keuangan,
    //         'startDate' => $startDate,
    //         'endDate' => $endDate,
    //         'perusahaan' => $perusahaan,
    //         'pemasukkan' => $pemasukkan,
    //         'pengeluaran' => $pengeluaran,
    //         'selisih' => $selisih
    //     ]);
    // }

    /**
     * Displays a single Keuangan model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel(decrypt($id)),
        ]);
    }

    /**
     * Creates a new Keuangan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Keuangan();
        $kode = Kode::listKode();
        $listUser = User::listUser();

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'kode' => $kode,
                'listUser' => $listUser
            ]);
        }
    }

    /**
     * Updates an existing Keuangan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

            return $this->redirect(['view', 'id' => decrypt($model->id)]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Keuangan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel(decrypt($model->id))->delete();
        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Keuangan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Keuangan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Keuangan::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\helpers\Url;
use yii\web\Response;
use yii\web\Controller;
use app\models\Keuangan;
use app\models\Struktur;
use app\models\LoginForm;
use app\models\Perusahaan;
use app\models\ContactForm;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $sumKeuangan = Keuangan::sumKeuangan();
        $totalKaryawan = Struktur::totalKaryawan();
        $findPerusahaan = Perusahaan::findDataPerusahaan(User::findUser()->id);
        $sumAsset = Keuangan::sumAsset();

        // debug(Keuangan::sumAsset());
        
        return $this->render('index', [
            'sumKeuangan' => $sumKeuangan,
            'totalKaryawan' => $totalKaryawan,
            'findPerusahaan' => $findPerusahaan,
            'sumAsset' => $sumAsset
        ]);
    }
    

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister()
    {
        $user = new User();
        $user->scenario = 'register';

        

        if ($user->load(Yii::$app->request->post()) && $user->register()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil Mendaftar, silahkan login'));
            return $this->redirect(['login']);
        }

        return $this->render('register', [
            'user' => $user
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Jabatan;
use yii\web\Controller;
use app\models\Struktur;
use app\models\UserMeta;
use yii\filters\VerbFilter;
use app\models\search\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for Users model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['deleted_at' => null]);
        $dataProvider->query->andWhere(['IN', 'id', Struktur::findKaryawanId()]);
        // debug(Struktur::findKaryawanId());

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel(decrypt($id));
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->create()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(decrypt($id));
        $model->scenario = 'update';
        $jabatan = Jabatan::listJabatan();

        if ($model->load(Yii::$app->request->post()) && $model->updateUser(decrypt($id))) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));
            return $this->redirect(['view', 'id' => encrypt($model->id)]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'jabatan' => $jabatan
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        User::softDelete(decrypt($id));
        
        Yii::$app->session->setFlash('success', Yii::t('app', 'Berhasil'));

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'Halaman yang diminta tidak ada.'));
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use app\models\User;
use yii\helpers\Url;



/* @var $this yii\web\View */

$this->title = $findPerusahaan->nama_perusahaan;
?>
<div class="site-index">

    <?php 
        echo $this->render('widget', [
            'totalKaryawan' => $totalKaryawan,
            'sumKeuangan' => $sumKeuangan,
            'sumAsset' => $sumAsset
        ]);
    ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Masuk';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Silakan isi kolom-kolom berikut untuk login: ')?></p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/widget.php
<?php

use yii\helpers\Url;

?>
<div class="row">
    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
        <div class="inner">
            <h3><?= $totalKaryawan?></h3>

            <p><?= Yii::t('app', 'Total Karyawan')?></p>
        </div>
        <div class="icon">
            <i class="fa fa-user-plus"></i>
        </div>
        <a href="<?= Url::to(['user/index'])?>" class="small-box-footer">
        <?= Yii::t('app', 'Selengkapnya')?> <i class="fa fa-arrow-circle-right"></i>
        </a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
        <div class="inner">
            <h3><?= Yii::$app->formatter->asCurrency($sumKeuangan)?></h3>

            <p><?= Yii::t('app', 'Total Keuangan')?></p>
        </div>
        <div class="icon">
            <i class="fa fa-money"></i>
        </div>
        <a href="<?= Url::to(['keuangan/index'])?>" class="small-box-footer">
        <?= Yii::t('app', 'Selengkapnya')?> <i class="fa fa-arrow-circle-right"></i>
        </a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-blue">
        <div class="inner">
            <h3><?= Yii::$app->formatter->asCurrency($sumAsset)?></h3>

            <p><?= Yii::t('app', 'Total Asset')?></p>
        </div>
        <div class="icon">
            <i class="fa fa-shopping-cart"></i>
        </div>
        <a href="<?= Url::to(['keuangan/index'])?>" class="small-box-footer">
        <?= Yii::t('app', 'Selengkapnya')?> <i class="fa fa-arrow-circle-right"></i>
        </a>
        </div>
    </div>
</div>